name: Jonathan Matthey
description: Portfolio
author: Jonathan Matthey
analytics: 
exclude: [ _design, README ]
# baseurl: "http://www.jonathanmatthey.com/redesign/_site/"
baseurl: "http://lips.github.io/jekyll-grid-portfolio-theme/"
